name: Update Gantt Chart

# Run the workflow on every push to the main branch
on:
  push:
    branches:
      - main

jobs:
  update-gantt:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Check out repository
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    # Step 3: Install dependencies from requirements.txt
    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt  # Ensure this file lists requests and other dependencies

    # Step 4: Run Python script to update diagram on push (diagram.py)
    - name: Run Python script to update Gantt chart
      env:
        JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        JIRA_PROJECT: ${{ secrets.JIRA_PROJECT }}
      run: |
        source venv/bin/activate
        python diagram.py

    # Step 5: Commit and push the updated README.md (if changed)
    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git add README.md
        git commit -m "Update Gantt chart in README"
        git push
      continue-on-error: true  # This ensures the workflow doesn't fail if there's no change to commit
